# docker-Specify the compose version
version: "3"

services:
  app:
    # build: .
    image: pudding/github-action-app:puppeteer-python-14-crawler-Course-Example-20231106-1201
    tty: true
    volumes: 
      - ./docker-build/startup.sh:/startup.sh
      - ./app:/app/
      - ./output:/output/
      - ./cache:/cache/